# Generated by Django 3.1.8 on 2021-06-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('climate', models.CharField(max_length=64)),
                ('diameter', models.DecimalField(decimal_places=3, max_digits=15)),
                ('gravity', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
                ('orbital_period', models.IntegerField()),
                ('population', models.IntegerField()),
                ('rotation_period', models.IntegerField()),
                ('surface_water', models.BooleanField(default=False)),
                ('terrain', models.CharField(max_length=32)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
