# Generated by Django 3.1.8 on 2021-05-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('export', models.FileField(upload_to='collections_exports/')),
                ('collection_type', models.IntegerField(choices=[(1, 'Characters'), (2, 'Worlds')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
