# Generated by Django 3.1.8 on 2021-05-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_extractions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataexport',
            name='collection_type',
            field=models.IntegerField(choices=[(1, 'Characters'), (2, 'Worlds')], db_index=True),
        ),
        migrations.AlterField(
            model_name='dataexport',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
