# Generated by Django 3.1.8 on 2021-06-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210604_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='analystuser',
            name='first_name',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='analystuser',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='analystuser',
            name='last_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
