# Generated by Django 3.1.8 on 2021-05-30 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('worlds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('height', models.IntegerField()),
                ('mass', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hair_color', models.CharField(max_length=32)),
                ('skin_color', models.CharField(max_length=32)),
                ('eye_color', models.CharField(max_length=32)),
                ('birth_year', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('home_world', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='people', to='worlds.planet')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
