# Generated by Django 3.1.8 on 2021-06-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_collections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='resolved_at',
            field=models.DateTimeField(null=True),
        ),
    ]
