# Generated by Django 3.1.8 on 2021-06-06 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_collections', '0002_datacollection_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollection',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_collections', to=settings.AUTH_USER_MODEL),
        ),
    ]
